-- Insertar/actualizar tabla Cliente
CREATE OR REPLACE PROCEDURE INSERT_CLIENTE( COD_CLIENTE NUMBER,
                                            NOMBRE_CLIENTE VARCHAR,
                                            DNI_CLIENTE NUMBER,
                                            TLF_CLIENTE NUMBER) IS

CLIENTCOUNT NUMBER;

BEGIN
    SELECT COUNT (*)
    INTO CLIENTCOUNT
    FROM PAPEL1.CLIENTE
    WHERE   COD_CLIENTE = CID;

    IF(CLIENTCOUNT > 0) THEN
        RAISE_APPLICATION_ERROR(-20006,'El cliente ya existe.');
    ELSE
        INSERT INTO PAPEL1.CLIENTE
        VALUES (COD_CLIENTE, NOMBRE_CLIENTE, DNI_CLIENTE, TLF_CLIENTE);

        INSERT INTO PAPEL2.CLIENTE
        VALUES (COD_CLIENTE, NOMBRE_CLIENTE, DNI_CLIENTE, TLF_CLIENTE);

        INSERT INTO PAPEL3.CLIENTE
        VALUES (COD_CLIENTE, NOMBRE_CLIENTE, DNI_CLIENTE, TLF_CLIENTE);

        INSERT INTO PAPEL4.CLIENTE
        VALUES (COD_CLIENTE, NOMBRE_CLIENTE, DNI_CLIENTE, TLF_CLIENTE);
    END IF;
END;
/