-- Insertar/actualizar tabla Proveedor
-- 16. Ningún proveedor será de otra ciudad distinta a Granada o a Sevilla.
CREATE OR REPLACE PROCEDURE INSERT_PROVEEDOR(   COD_PROVEEDOR NUMBER,
                                                NOMBRE_PRO VARCHAR,
                                                LOCALIDAD VARCHAR) IS

PCOUNT NUMBER;

BEGIN
    IF (LOCALIDAD = 'Granada') THEN
        INSERT INTO PAPEL1.PROVEEDOR1
        VALUES (COD_PROVEEDOR, NOMBRE_PRO , LOCALIDAD);

        INSERT INTO PAPEL4.PROVEEDOR1
        VALUES (COD_PROVEEDOR, NOMBRE_PRO , LOCALIDAD);
    
    ELSIF (LOCALIDAD = 'Sevilla') THEN
        INSERT INTO PAPEL3.PROVEEDOR2
        VALUES (COD_PROVEEDOR, NOMBRE_PRO , LOCALIDAD);

        INSERT INTO PAPEL2.PROVEEDOR2
        VALUES (COD_PROVEEDOR, NOMBRE_PRO , LOCALIDAD);
    ELSE
        RAISE_APPLICATION_ERROR(-20025,'LOCALIDAD NO VÁLIDA');
    END IF;
END;
/

--11. Dar de baja a un proveedor. Argumento: Código de proveedor.
CREATE OR REPLACE PROCEDURE DELETE_PROVEEDOR(COD_PRO NUMBER) IS
PROCOUNT NUMBER;
LOCALIDAD VARCHAR(20);

BEGIN
	SELECT COUNT (*)
	INTO PROCOUNT
	FROM PROVEEDOR
	WHERE COD_PRO = PID;

    IF(PROCOUNT = 0) THEN
        RAISE_APPLICATION_ERROR(-20026,'Este codigo de proveedor no se encuentra registrado.');
    END IF;

	SELECT PROVINCIA
	INTO LOCALIDAD
    FROM PROVEEDOR
    WHERE COD_PRO = PID;

	IF(LOCALIDAD = 'Granada') THEN
		DELETE FROM PAPEL1.PROVEEDOR1 WHERE COD_PRO = PID;
		DELETE FROM PAPEL4.PROVEEDOR1 WHERE COD_PRO = PID;

	ELSIF (LOCALIDAD = 'Sevilla') THEN
		DELETE FROM PAPEL2.PROVEEDOR2 WHERE COD_PRO = PID;
		DELETE FROM PAPEL3.PROVEEDOR2 WHERE COD_PRO = PID;
    ELSE
        RAISE_APPLICATION_ERROR(-20027,'LOCALIDAD NO VÁLIDA');
    END IF;
END;
/