-- DROPS
DROP TABLE EMPLEADO17;

DROP TABLE RESERVA17;

DROP TABLE CLIENTE;

DROP TABLE ENTREGA17;

DROP TABLE HOTEL17;

DROP TABLE ARTICULO;

DROP TABLE PROVEEDOR1;

-- TABLES
CREATE TABLE HOTEL17(
	HID NUMBER NOT NULL,
	EID NUMBER,
	NOMBRE VARCHAR(50) NOT NULL,
	CIUDAD VARCHAR(20) NOT NULL,
	PROVINCIA VARCHAR(10) NOT NULL,
	N_HAB NUMBER NOT NULL,
	N_HAB2 NUMBER NOT NULL,
	PRIMARY KEY(HID)
);

CREATE TABLE PROVEEDOR1(
	PID NUMBER NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	PROVINCIA VARCHAR(10) NOT NULL,
	PRIMARY KEY(PID)
);

CREATE TABLE ARTICULO(
	PID NUMBER NOT NULL,
	AID NUMBER NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
	PRIMARY KEY(PID, AID)
);

CREATE TABLE ENTREGA17(
	PID NUMBER NOT NULL,
	AID NUMBER NOT NULL,
	HID NUMBER NOT NULL REFERENCES HOTEL17(HID),
	FECHA DATE NOT NULL,
	PRECIO NUMBER NOT NULL,
	CANTIDAD NUMBER NOT NULL,
	PRIMARY KEY(PID, AID, HID, FECHA),
	FOREIGN KEY(PID,AID) REFERENCES ARTICULO(PID, AID)
);

CREATE TABLE EMPLEADO17(
	EID NUMBER NOT NULL,
	HID NUMBER NOT NULL REFERENCES HOTEL17(HID),
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(70) NOT NULL,
	SALARIO NUMBER NOT NULL,
	DNI NUMBER NOT NULL,
	TLF NUMBER NOT NULL,
	FECHA_CONTRATO DATE NOT NULL,
	FECHA_INI DATE NOT NULL,
	PRIMARY KEY(EID)
);

CREATE TABLE CLIENTE(
	CID NUMBER NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	DNI NUMBER NOT NULL,
	TLF NUMBER NOT NULL,
	PRIMARY KEY(CID)
);

CREATE TABLE RESERVA17(
	CID NUMBER NOT NULL REFERENCES CLIENTE(CID),
	HID NUMBER NOT NULL REFERENCES HOTEL17(HID),
	FECHA_FIN DATE NOT NULL,
	FECHA_INI DATE NOT NULL,
	TIPO_HAB VARCHAR(20) NOT NULL,
	PRECIO NUMBER NOT NULL,
	PRIMARY KEY(CID, HID, FECHA_FIN, FECHA_INI)
);

-- GRANTS
GRANT DELETE, INSERT, UPDATE, SELECT
ON ARTICULO
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON CLIENTE
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON EMPLEADO17
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON ENTREGA17
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON HOTEL17
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON PROVEEDOR1
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON RESERVA17
TO PAPEL2,PAPEL3,PAPEL4;
commit;