GRANT DELETE, INSERT, UPDATE, SELECT
ON ARTICULO
TO PAPEL1,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON CLIENTE
TO PAPEL1,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON EMPLEADO36
TO PAPEL1,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON ENTREGA36
TO PAPEL1,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON HOTEL36
TO PAPEL1,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON PROVEEDOR2
TO PAPEL1,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON RESERVA36
TO PAPEL1,PAPEL3,PAPEL4;
commit;
