GRANT DELETE, INSERT, UPDATE, SELECT
ON ARTICULO
TO PAPEL1,PAPEL2,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON CLIENTE
TO PAPEL1,PAPEL2,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON EMPLEADO25
TO PAPEL1,PAPEL2,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON ENTREGA25
TO PAPEL1,PAPEL2,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON HOTEL25
TO PAPEL1,PAPEL2,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON PROVEEDOR2
TO PAPEL1,PAPEL2,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON RESERVA25
TO PAPEL1,PAPEL2,PAPEL4;
commit;
