GRANT DELETE, INSERT, UPDATE, SELECT
ON ARTICULO
TO PAPEL1,PAPEL2,PAPEL3;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON EMPLEADO48
TO PAPEL1,PAPEL2,PAPEL3;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON ENTREGA48
TO PAPEL1,PAPEL2,PAPEL3;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON HOTEL48
TO PAPEL1,PAPEL2,PAPEL3;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON PROVEEDOR1
TO PAPEL1,PAPEL2,PAPEL3;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON RESERVA48
TO PAPEL1,PAPEL2,PAPEL3;
commit;
