GRANT DELETE, INSERT, UPDATE, SELECT
ON ARTICULO
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON CLIENTE
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON EMPLEADO17
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON ENTREGA17
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON HOTEL17
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON PROVEEDOR1
TO PAPEL2,PAPEL3,PAPEL4;
commit;

GRANT DELETE, INSERT, UPDATE, SELECT
ON RESERVA17
TO PAPEL2,PAPEL3,PAPEL4;
commit;
